spring.datasource.url=jdbc:mysql://dpg-d2i6mmu3jp1c739446rg-a:5432/backend_db_rmd7
spring.datasource.username=backend_db_rmd7_user
spring.datasource.password=Jsm4vqRImhrb0sFsGbGqX09gRTiHsHXo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
